/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TdBadge {
    'color': string;
  }
  interface TdButton {
    'color': string;
    'disabled': boolean;
    'fill': string;
    'size': string;
  }
  interface TdCard {
    'color': string;
    'disabled': boolean;
    'fill': string;
    'size': string;
  }
  interface TdForm {
    'color': string;
    'disabled': boolean;
    'fill': string;
    'size': string;
  }
  interface TdPagination {
    'color': string;
    'disabled': boolean;
    'fill': string;
    'size': string;
  }
}

declare global {


  interface HTMLTdBadgeElement extends Components.TdBadge, HTMLStencilElement {}
  var HTMLTdBadgeElement: {
    prototype: HTMLTdBadgeElement;
    new (): HTMLTdBadgeElement;
  };

  interface HTMLTdButtonElement extends Components.TdButton, HTMLStencilElement {}
  var HTMLTdButtonElement: {
    prototype: HTMLTdButtonElement;
    new (): HTMLTdButtonElement;
  };

  interface HTMLTdCardElement extends Components.TdCard, HTMLStencilElement {}
  var HTMLTdCardElement: {
    prototype: HTMLTdCardElement;
    new (): HTMLTdCardElement;
  };

  interface HTMLTdFormElement extends Components.TdForm, HTMLStencilElement {}
  var HTMLTdFormElement: {
    prototype: HTMLTdFormElement;
    new (): HTMLTdFormElement;
  };

  interface HTMLTdPaginationElement extends Components.TdPagination, HTMLStencilElement {}
  var HTMLTdPaginationElement: {
    prototype: HTMLTdPaginationElement;
    new (): HTMLTdPaginationElement;
  };
  interface HTMLElementTagNameMap {
    'td-badge': HTMLTdBadgeElement;
    'td-button': HTMLTdButtonElement;
    'td-card': HTMLTdCardElement;
    'td-form': HTMLTdFormElement;
    'td-pagination': HTMLTdPaginationElement;
  }
}

declare namespace LocalJSX {
  interface TdBadge extends JSXBase.HTMLAttributes<HTMLTdBadgeElement> {
    'color'?: string;
  }
  interface TdButton extends JSXBase.HTMLAttributes<HTMLTdButtonElement> {
    'color'?: string;
    'disabled'?: boolean;
    'fill'?: string;
    'size'?: string;
  }
  interface TdCard extends JSXBase.HTMLAttributes<HTMLTdCardElement> {
    'color'?: string;
    'disabled'?: boolean;
    'fill'?: string;
    'size'?: string;
  }
  interface TdForm extends JSXBase.HTMLAttributes<HTMLTdFormElement> {
    'color'?: string;
    'disabled'?: boolean;
    'fill'?: string;
    'size'?: string;
  }
  interface TdPagination extends JSXBase.HTMLAttributes<HTMLTdPaginationElement> {
    'color'?: string;
    'disabled'?: boolean;
    'fill'?: string;
    'size'?: string;
  }

  interface IntrinsicElements {
    'td-badge': TdBadge;
    'td-button': TdButton;
    'td-card': TdCard;
    'td-form': TdForm;
    'td-pagination': TdPagination;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


