/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TdBadge {
    'color': string;
  }
  interface TdButton {
    'color': string;
    'disabled': boolean;
    'fill': string;
    'size': string;
  }
}

declare global {


  interface HTMLTdBadgeElement extends Components.TdBadge, HTMLStencilElement {}
  var HTMLTdBadgeElement: {
    prototype: HTMLTdBadgeElement;
    new (): HTMLTdBadgeElement;
  };

  interface HTMLTdButtonElement extends Components.TdButton, HTMLStencilElement {}
  var HTMLTdButtonElement: {
    prototype: HTMLTdButtonElement;
    new (): HTMLTdButtonElement;
  };
  interface HTMLElementTagNameMap {
    'td-badge': HTMLTdBadgeElement;
    'td-button': HTMLTdButtonElement;
  }
}

declare namespace LocalJSX {
  interface TdBadge extends JSXBase.HTMLAttributes<HTMLTdBadgeElement> {
    'color'?: string;
  }
  interface TdButton extends JSXBase.HTMLAttributes<HTMLTdButtonElement> {
    'color'?: string;
    'disabled'?: boolean;
    'fill'?: string;
    'size'?: string;
  }

  interface IntrinsicElements {
    'td-badge': TdBadge;
    'td-button': TdButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


